language: generic 

sudo: required

services:
  - docker 

# before_install:
#   - docker build -t docker-test .

# script:
#   docker run docker-test
# after_deploy:
#   - echo "done deploying"

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIA5BZHLSWDQ4RWP26I"
  secret_access_key: "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"
  region: "us-east-1"
  app: 'docker-react' 
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-897193842055'
  bucket_path: 'docker-react'
  on:
    branch: master